
version: 2

models:
    - name: CustomerandOrder
      description: "Customer and total order amount exceeding 2M"
      columns:
          - name: CUSTKEY
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: TimeIncr
      description: "test incremental load"
      columns:
          - name: T_TIME_ID
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
                
   